CREATE TABLE `projection_agents` (
	`access_data` text,
	`access_observed_at` integer,
	`access_source` text,
	`entity_id` text NOT NULL,
	`identity_data` text,
	`identity_observed_at` integer,
	`identity_source` text,
	`profile_data` text,
	`profile_observed_at` integer,
	`profile_source` text,
	`routing_data` text,
	`routing_observed_at` integer,
	`routing_source` text,
	`runtime_data` text,
	`runtime_observed_at` integer,
	`runtime_source` text,
	`schema_version` integer DEFAULT 1 NOT NULL,
	`scope` text NOT NULL,
	`storage_id` text PRIMARY KEY NOT NULL,
	`tombstone_at` integer,
	CONSTRAINT "projection_agents_schema_version_current" CHECK("projection_agents"."schema_version" = 1),
	CONSTRAINT "projection_agents_tombstone_at_positive" CHECK("projection_agents"."tombstone_at" IS NULL OR "projection_agents"."tombstone_at" >= 0),
	CONSTRAINT "projection_agents_access_complete" CHECK((("projection_agents"."access_data" IS NULL) = ("projection_agents"."access_observed_at" IS NULL)) AND (("projection_agents"."access_data" IS NULL) = ("projection_agents"."access_source" IS NULL))),
	CONSTRAINT "projection_agents_access_data_json" CHECK("projection_agents"."access_data" IS NULL OR json_valid("projection_agents"."access_data")),
	CONSTRAINT "projection_agents_access_observed_at_positive" CHECK("projection_agents"."access_observed_at" IS NULL OR "projection_agents"."access_observed_at" >= 0),
	CONSTRAINT "projection_agents_access_source_valid" CHECK("projection_agents"."access_source" IS NULL OR "projection_agents"."access_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_agents_identity_complete" CHECK((("projection_agents"."identity_data" IS NULL) = ("projection_agents"."identity_observed_at" IS NULL)) AND (("projection_agents"."identity_data" IS NULL) = ("projection_agents"."identity_source" IS NULL))),
	CONSTRAINT "projection_agents_identity_data_json" CHECK("projection_agents"."identity_data" IS NULL OR json_valid("projection_agents"."identity_data")),
	CONSTRAINT "projection_agents_identity_observed_at_positive" CHECK("projection_agents"."identity_observed_at" IS NULL OR "projection_agents"."identity_observed_at" >= 0),
	CONSTRAINT "projection_agents_identity_source_valid" CHECK("projection_agents"."identity_source" IS NULL OR "projection_agents"."identity_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_agents_profile_complete" CHECK((("projection_agents"."profile_data" IS NULL) = ("projection_agents"."profile_observed_at" IS NULL)) AND (("projection_agents"."profile_data" IS NULL) = ("projection_agents"."profile_source" IS NULL))),
	CONSTRAINT "projection_agents_profile_data_json" CHECK("projection_agents"."profile_data" IS NULL OR json_valid("projection_agents"."profile_data")),
	CONSTRAINT "projection_agents_profile_observed_at_positive" CHECK("projection_agents"."profile_observed_at" IS NULL OR "projection_agents"."profile_observed_at" >= 0),
	CONSTRAINT "projection_agents_profile_source_valid" CHECK("projection_agents"."profile_source" IS NULL OR "projection_agents"."profile_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_agents_routing_complete" CHECK((("projection_agents"."routing_data" IS NULL) = ("projection_agents"."routing_observed_at" IS NULL)) AND (("projection_agents"."routing_data" IS NULL) = ("projection_agents"."routing_source" IS NULL))),
	CONSTRAINT "projection_agents_routing_data_json" CHECK("projection_agents"."routing_data" IS NULL OR json_valid("projection_agents"."routing_data")),
	CONSTRAINT "projection_agents_routing_observed_at_positive" CHECK("projection_agents"."routing_observed_at" IS NULL OR "projection_agents"."routing_observed_at" >= 0),
	CONSTRAINT "projection_agents_routing_source_valid" CHECK("projection_agents"."routing_source" IS NULL OR "projection_agents"."routing_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_agents_runtime_complete" CHECK((("projection_agents"."runtime_data" IS NULL) = ("projection_agents"."runtime_observed_at" IS NULL)) AND (("projection_agents"."runtime_data" IS NULL) = ("projection_agents"."runtime_source" IS NULL))),
	CONSTRAINT "projection_agents_runtime_data_json" CHECK("projection_agents"."runtime_data" IS NULL OR json_valid("projection_agents"."runtime_data")),
	CONSTRAINT "projection_agents_runtime_observed_at_positive" CHECK("projection_agents"."runtime_observed_at" IS NULL OR "projection_agents"."runtime_observed_at" >= 0),
	CONSTRAINT "projection_agents_runtime_source_valid" CHECK("projection_agents"."runtime_source" IS NULL OR "projection_agents"."runtime_source" IN ('mutation', 'network', 'realtime'))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `projection_agents_scope_entity_unique` ON `projection_agents` (`scope`,`entity_id`);--> statement-breakpoint
CREATE INDEX `projection_agents_scope_idx` ON `projection_agents` (`scope`);--> statement-breakpoint
CREATE TABLE `projection_briefs` (
	`actions_data` text,
	`actions_observed_at` integer,
	`actions_source` text,
	`content_data` text,
	`content_observed_at` integer,
	`content_source` text,
	`entity_id` text NOT NULL,
	`read_state_data` text,
	`read_state_observed_at` integer,
	`read_state_source` text,
	`relations_data` text,
	`relations_observed_at` integer,
	`relations_source` text,
	`resolution_data` text,
	`resolution_observed_at` integer,
	`resolution_source` text,
	`schema_version` integer DEFAULT 1 NOT NULL,
	`scope` text NOT NULL,
	`storage_id` text PRIMARY KEY NOT NULL,
	`tombstone_at` integer,
	CONSTRAINT "projection_briefs_schema_version_current" CHECK("projection_briefs"."schema_version" = 1),
	CONSTRAINT "projection_briefs_tombstone_at_positive" CHECK("projection_briefs"."tombstone_at" IS NULL OR "projection_briefs"."tombstone_at" >= 0),
	CONSTRAINT "projection_briefs_actions_complete" CHECK((("projection_briefs"."actions_data" IS NULL) = ("projection_briefs"."actions_observed_at" IS NULL)) AND (("projection_briefs"."actions_data" IS NULL) = ("projection_briefs"."actions_source" IS NULL))),
	CONSTRAINT "projection_briefs_actions_data_json" CHECK("projection_briefs"."actions_data" IS NULL OR json_valid("projection_briefs"."actions_data")),
	CONSTRAINT "projection_briefs_actions_observed_at_positive" CHECK("projection_briefs"."actions_observed_at" IS NULL OR "projection_briefs"."actions_observed_at" >= 0),
	CONSTRAINT "projection_briefs_actions_source_valid" CHECK("projection_briefs"."actions_source" IS NULL OR "projection_briefs"."actions_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_briefs_content_complete" CHECK((("projection_briefs"."content_data" IS NULL) = ("projection_briefs"."content_observed_at" IS NULL)) AND (("projection_briefs"."content_data" IS NULL) = ("projection_briefs"."content_source" IS NULL))),
	CONSTRAINT "projection_briefs_content_data_json" CHECK("projection_briefs"."content_data" IS NULL OR json_valid("projection_briefs"."content_data")),
	CONSTRAINT "projection_briefs_content_observed_at_positive" CHECK("projection_briefs"."content_observed_at" IS NULL OR "projection_briefs"."content_observed_at" >= 0),
	CONSTRAINT "projection_briefs_content_source_valid" CHECK("projection_briefs"."content_source" IS NULL OR "projection_briefs"."content_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_briefs_read_state_complete" CHECK((("projection_briefs"."read_state_data" IS NULL) = ("projection_briefs"."read_state_observed_at" IS NULL)) AND (("projection_briefs"."read_state_data" IS NULL) = ("projection_briefs"."read_state_source" IS NULL))),
	CONSTRAINT "projection_briefs_read_state_data_json" CHECK("projection_briefs"."read_state_data" IS NULL OR json_valid("projection_briefs"."read_state_data")),
	CONSTRAINT "projection_briefs_read_state_observed_at_positive" CHECK("projection_briefs"."read_state_observed_at" IS NULL OR "projection_briefs"."read_state_observed_at" >= 0),
	CONSTRAINT "projection_briefs_read_state_source_valid" CHECK("projection_briefs"."read_state_source" IS NULL OR "projection_briefs"."read_state_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_briefs_relations_complete" CHECK((("projection_briefs"."relations_data" IS NULL) = ("projection_briefs"."relations_observed_at" IS NULL)) AND (("projection_briefs"."relations_data" IS NULL) = ("projection_briefs"."relations_source" IS NULL))),
	CONSTRAINT "projection_briefs_relations_data_json" CHECK("projection_briefs"."relations_data" IS NULL OR json_valid("projection_briefs"."relations_data")),
	CONSTRAINT "projection_briefs_relations_observed_at_positive" CHECK("projection_briefs"."relations_observed_at" IS NULL OR "projection_briefs"."relations_observed_at" >= 0),
	CONSTRAINT "projection_briefs_relations_source_valid" CHECK("projection_briefs"."relations_source" IS NULL OR "projection_briefs"."relations_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_briefs_resolution_complete" CHECK((("projection_briefs"."resolution_data" IS NULL) = ("projection_briefs"."resolution_observed_at" IS NULL)) AND (("projection_briefs"."resolution_data" IS NULL) = ("projection_briefs"."resolution_source" IS NULL))),
	CONSTRAINT "projection_briefs_resolution_data_json" CHECK("projection_briefs"."resolution_data" IS NULL OR json_valid("projection_briefs"."resolution_data")),
	CONSTRAINT "projection_briefs_resolution_observed_at_positive" CHECK("projection_briefs"."resolution_observed_at" IS NULL OR "projection_briefs"."resolution_observed_at" >= 0),
	CONSTRAINT "projection_briefs_resolution_source_valid" CHECK("projection_briefs"."resolution_source" IS NULL OR "projection_briefs"."resolution_source" IN ('mutation', 'network', 'realtime'))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `projection_briefs_scope_entity_unique` ON `projection_briefs` (`scope`,`entity_id`);--> statement-breakpoint
CREATE INDEX `projection_briefs_scope_idx` ON `projection_briefs` (`scope`);--> statement-breakpoint
CREATE TABLE `projection_chat_groups` (
	`access_data` text,
	`access_observed_at` integer,
	`access_source` text,
	`entity_id` text NOT NULL,
	`identity_data` text,
	`identity_observed_at` integer,
	`identity_source` text,
	`schema_version` integer DEFAULT 1 NOT NULL,
	`scope` text NOT NULL,
	`storage_id` text PRIMARY KEY NOT NULL,
	`tombstone_at` integer,
	CONSTRAINT "projection_chat_groups_schema_version_current" CHECK("projection_chat_groups"."schema_version" = 1),
	CONSTRAINT "projection_chat_groups_tombstone_at_positive" CHECK("projection_chat_groups"."tombstone_at" IS NULL OR "projection_chat_groups"."tombstone_at" >= 0),
	CONSTRAINT "projection_chat_groups_access_complete" CHECK((("projection_chat_groups"."access_data" IS NULL) = ("projection_chat_groups"."access_observed_at" IS NULL)) AND (("projection_chat_groups"."access_data" IS NULL) = ("projection_chat_groups"."access_source" IS NULL))),
	CONSTRAINT "projection_chat_groups_access_data_json" CHECK("projection_chat_groups"."access_data" IS NULL OR json_valid("projection_chat_groups"."access_data")),
	CONSTRAINT "projection_chat_groups_access_observed_at_positive" CHECK("projection_chat_groups"."access_observed_at" IS NULL OR "projection_chat_groups"."access_observed_at" >= 0),
	CONSTRAINT "projection_chat_groups_access_source_valid" CHECK("projection_chat_groups"."access_source" IS NULL OR "projection_chat_groups"."access_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_chat_groups_identity_complete" CHECK((("projection_chat_groups"."identity_data" IS NULL) = ("projection_chat_groups"."identity_observed_at" IS NULL)) AND (("projection_chat_groups"."identity_data" IS NULL) = ("projection_chat_groups"."identity_source" IS NULL))),
	CONSTRAINT "projection_chat_groups_identity_data_json" CHECK("projection_chat_groups"."identity_data" IS NULL OR json_valid("projection_chat_groups"."identity_data")),
	CONSTRAINT "projection_chat_groups_identity_observed_at_positive" CHECK("projection_chat_groups"."identity_observed_at" IS NULL OR "projection_chat_groups"."identity_observed_at" >= 0),
	CONSTRAINT "projection_chat_groups_identity_source_valid" CHECK("projection_chat_groups"."identity_source" IS NULL OR "projection_chat_groups"."identity_source" IN ('mutation', 'network', 'realtime'))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `projection_chat_groups_scope_entity_unique` ON `projection_chat_groups` (`scope`,`entity_id`);--> statement-breakpoint
CREATE INDEX `projection_chat_groups_scope_idx` ON `projection_chat_groups` (`scope`);--> statement-breakpoint
CREATE TABLE `projection_home_indexes` (
	`data` text NOT NULL,
	`key` text NOT NULL,
	`observed_at` integer NOT NULL,
	`schema_version` integer DEFAULT 1 NOT NULL,
	`scope` text NOT NULL,
	`source` text NOT NULL,
	`storage_id` text PRIMARY KEY NOT NULL,
	CONSTRAINT "projection_home_indexes_data_json" CHECK(json_valid("projection_home_indexes"."data")),
	CONSTRAINT "projection_home_indexes_key_valid" CHECK("projection_home_indexes"."key" IN ('home.inboxTopics', 'home.recentTopics', 'home.sidebar', 'home.tasks', 'home.unresolvedBriefs')),
	CONSTRAINT "projection_home_indexes_observed_at_positive" CHECK("projection_home_indexes"."observed_at" >= 0),
	CONSTRAINT "projection_home_indexes_schema_version_current" CHECK("projection_home_indexes"."schema_version" = 1),
	CONSTRAINT "projection_home_indexes_source_valid" CHECK("projection_home_indexes"."source" IN ('mutation', 'network', 'realtime'))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `projection_home_indexes_scope_key_unique` ON `projection_home_indexes` (`scope`,`key`);--> statement-breakpoint
CREATE INDEX `projection_home_indexes_scope_idx` ON `projection_home_indexes` (`scope`);--> statement-breakpoint
CREATE TABLE `projection_home_snapshots` (
	`data` text NOT NULL,
	`key` text NOT NULL,
	`observed_at` integer NOT NULL,
	`schema_version` integer DEFAULT 1 NOT NULL,
	`scope` text NOT NULL,
	`source` text NOT NULL,
	`storage_id` text PRIMARY KEY NOT NULL,
	CONSTRAINT "projection_home_snapshots_data_json" CHECK(json_valid("projection_home_snapshots"."data")),
	CONSTRAINT "projection_home_snapshots_key_valid" CHECK("projection_home_snapshots"."key" = 'home.dailyBrief'),
	CONSTRAINT "projection_home_snapshots_observed_at_positive" CHECK("projection_home_snapshots"."observed_at" >= 0),
	CONSTRAINT "projection_home_snapshots_schema_version_current" CHECK("projection_home_snapshots"."schema_version" = 1),
	CONSTRAINT "projection_home_snapshots_source_valid" CHECK("projection_home_snapshots"."source" IN ('mutation', 'network', 'realtime'))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `projection_home_snapshots_scope_key_unique` ON `projection_home_snapshots` (`scope`,`key`);--> statement-breakpoint
CREATE INDEX `projection_home_snapshots_scope_idx` ON `projection_home_snapshots` (`scope`);--> statement-breakpoint
CREATE TABLE `projection_tasks` (
	`assignment_data` text,
	`assignment_observed_at` integer,
	`assignment_source` text,
	`description_data` text,
	`description_observed_at` integer,
	`description_source` text,
	`display_data` text,
	`display_observed_at` integer,
	`display_source` text,
	`entity_id` text NOT NULL,
	`identity_data` text,
	`identity_observed_at` integer,
	`identity_source` text,
	`lifecycle_data` text,
	`lifecycle_observed_at` integer,
	`lifecycle_source` text,
	`schema_version` integer DEFAULT 1 NOT NULL,
	`scope` text NOT NULL,
	`storage_id` text PRIMARY KEY NOT NULL,
	`tombstone_at` integer,
	CONSTRAINT "projection_tasks_schema_version_current" CHECK("projection_tasks"."schema_version" = 1),
	CONSTRAINT "projection_tasks_tombstone_at_positive" CHECK("projection_tasks"."tombstone_at" IS NULL OR "projection_tasks"."tombstone_at" >= 0),
	CONSTRAINT "projection_tasks_assignment_complete" CHECK((("projection_tasks"."assignment_data" IS NULL) = ("projection_tasks"."assignment_observed_at" IS NULL)) AND (("projection_tasks"."assignment_data" IS NULL) = ("projection_tasks"."assignment_source" IS NULL))),
	CONSTRAINT "projection_tasks_assignment_data_json" CHECK("projection_tasks"."assignment_data" IS NULL OR json_valid("projection_tasks"."assignment_data")),
	CONSTRAINT "projection_tasks_assignment_observed_at_positive" CHECK("projection_tasks"."assignment_observed_at" IS NULL OR "projection_tasks"."assignment_observed_at" >= 0),
	CONSTRAINT "projection_tasks_assignment_source_valid" CHECK("projection_tasks"."assignment_source" IS NULL OR "projection_tasks"."assignment_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_tasks_description_complete" CHECK((("projection_tasks"."description_data" IS NULL) = ("projection_tasks"."description_observed_at" IS NULL)) AND (("projection_tasks"."description_data" IS NULL) = ("projection_tasks"."description_source" IS NULL))),
	CONSTRAINT "projection_tasks_description_data_json" CHECK("projection_tasks"."description_data" IS NULL OR json_valid("projection_tasks"."description_data")),
	CONSTRAINT "projection_tasks_description_observed_at_positive" CHECK("projection_tasks"."description_observed_at" IS NULL OR "projection_tasks"."description_observed_at" >= 0),
	CONSTRAINT "projection_tasks_description_source_valid" CHECK("projection_tasks"."description_source" IS NULL OR "projection_tasks"."description_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_tasks_display_complete" CHECK((("projection_tasks"."display_data" IS NULL) = ("projection_tasks"."display_observed_at" IS NULL)) AND (("projection_tasks"."display_data" IS NULL) = ("projection_tasks"."display_source" IS NULL))),
	CONSTRAINT "projection_tasks_display_data_json" CHECK("projection_tasks"."display_data" IS NULL OR json_valid("projection_tasks"."display_data")),
	CONSTRAINT "projection_tasks_display_observed_at_positive" CHECK("projection_tasks"."display_observed_at" IS NULL OR "projection_tasks"."display_observed_at" >= 0),
	CONSTRAINT "projection_tasks_display_source_valid" CHECK("projection_tasks"."display_source" IS NULL OR "projection_tasks"."display_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_tasks_identity_complete" CHECK((("projection_tasks"."identity_data" IS NULL) = ("projection_tasks"."identity_observed_at" IS NULL)) AND (("projection_tasks"."identity_data" IS NULL) = ("projection_tasks"."identity_source" IS NULL))),
	CONSTRAINT "projection_tasks_identity_data_json" CHECK("projection_tasks"."identity_data" IS NULL OR json_valid("projection_tasks"."identity_data")),
	CONSTRAINT "projection_tasks_identity_observed_at_positive" CHECK("projection_tasks"."identity_observed_at" IS NULL OR "projection_tasks"."identity_observed_at" >= 0),
	CONSTRAINT "projection_tasks_identity_source_valid" CHECK("projection_tasks"."identity_source" IS NULL OR "projection_tasks"."identity_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_tasks_lifecycle_complete" CHECK((("projection_tasks"."lifecycle_data" IS NULL) = ("projection_tasks"."lifecycle_observed_at" IS NULL)) AND (("projection_tasks"."lifecycle_data" IS NULL) = ("projection_tasks"."lifecycle_source" IS NULL))),
	CONSTRAINT "projection_tasks_lifecycle_data_json" CHECK("projection_tasks"."lifecycle_data" IS NULL OR json_valid("projection_tasks"."lifecycle_data")),
	CONSTRAINT "projection_tasks_lifecycle_observed_at_positive" CHECK("projection_tasks"."lifecycle_observed_at" IS NULL OR "projection_tasks"."lifecycle_observed_at" >= 0),
	CONSTRAINT "projection_tasks_lifecycle_source_valid" CHECK("projection_tasks"."lifecycle_source" IS NULL OR "projection_tasks"."lifecycle_source" IN ('mutation', 'network', 'realtime'))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `projection_tasks_scope_entity_unique` ON `projection_tasks` (`scope`,`entity_id`);--> statement-breakpoint
CREATE INDEX `projection_tasks_scope_idx` ON `projection_tasks` (`scope`);--> statement-breakpoint
CREATE TABLE `projection_topics` (
	`activity_data` text,
	`activity_observed_at` integer,
	`activity_source` text,
	`creation_data` text,
	`creation_observed_at` integer,
	`creation_source` text,
	`display_data` text,
	`display_observed_at` integer,
	`display_source` text,
	`entity_id` text NOT NULL,
	`navigation_data` text,
	`navigation_observed_at` integer,
	`navigation_source` text,
	`preview_data` text,
	`preview_observed_at` integer,
	`preview_source` text,
	`routing_data` text,
	`routing_observed_at` integer,
	`routing_source` text,
	`run_timing_data` text,
	`run_timing_observed_at` integer,
	`run_timing_source` text,
	`schema_version` integer DEFAULT 1 NOT NULL,
	`scope` text NOT NULL,
	`status_data` text,
	`status_observed_at` integer,
	`status_source` text,
	`storage_id` text PRIMARY KEY NOT NULL,
	`tombstone_at` integer,
	CONSTRAINT "projection_topics_schema_version_current" CHECK("projection_topics"."schema_version" = 1),
	CONSTRAINT "projection_topics_tombstone_at_positive" CHECK("projection_topics"."tombstone_at" IS NULL OR "projection_topics"."tombstone_at" >= 0),
	CONSTRAINT "projection_topics_activity_complete" CHECK((("projection_topics"."activity_data" IS NULL) = ("projection_topics"."activity_observed_at" IS NULL)) AND (("projection_topics"."activity_data" IS NULL) = ("projection_topics"."activity_source" IS NULL))),
	CONSTRAINT "projection_topics_activity_data_json" CHECK("projection_topics"."activity_data" IS NULL OR json_valid("projection_topics"."activity_data")),
	CONSTRAINT "projection_topics_activity_observed_at_positive" CHECK("projection_topics"."activity_observed_at" IS NULL OR "projection_topics"."activity_observed_at" >= 0),
	CONSTRAINT "projection_topics_activity_source_valid" CHECK("projection_topics"."activity_source" IS NULL OR "projection_topics"."activity_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_topics_creation_complete" CHECK((("projection_topics"."creation_data" IS NULL) = ("projection_topics"."creation_observed_at" IS NULL)) AND (("projection_topics"."creation_data" IS NULL) = ("projection_topics"."creation_source" IS NULL))),
	CONSTRAINT "projection_topics_creation_data_json" CHECK("projection_topics"."creation_data" IS NULL OR json_valid("projection_topics"."creation_data")),
	CONSTRAINT "projection_topics_creation_observed_at_positive" CHECK("projection_topics"."creation_observed_at" IS NULL OR "projection_topics"."creation_observed_at" >= 0),
	CONSTRAINT "projection_topics_creation_source_valid" CHECK("projection_topics"."creation_source" IS NULL OR "projection_topics"."creation_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_topics_display_complete" CHECK((("projection_topics"."display_data" IS NULL) = ("projection_topics"."display_observed_at" IS NULL)) AND (("projection_topics"."display_data" IS NULL) = ("projection_topics"."display_source" IS NULL))),
	CONSTRAINT "projection_topics_display_data_json" CHECK("projection_topics"."display_data" IS NULL OR json_valid("projection_topics"."display_data")),
	CONSTRAINT "projection_topics_display_observed_at_positive" CHECK("projection_topics"."display_observed_at" IS NULL OR "projection_topics"."display_observed_at" >= 0),
	CONSTRAINT "projection_topics_display_source_valid" CHECK("projection_topics"."display_source" IS NULL OR "projection_topics"."display_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_topics_navigation_complete" CHECK((("projection_topics"."navigation_data" IS NULL) = ("projection_topics"."navigation_observed_at" IS NULL)) AND (("projection_topics"."navigation_data" IS NULL) = ("projection_topics"."navigation_source" IS NULL))),
	CONSTRAINT "projection_topics_navigation_data_json" CHECK("projection_topics"."navigation_data" IS NULL OR json_valid("projection_topics"."navigation_data")),
	CONSTRAINT "projection_topics_navigation_observed_at_positive" CHECK("projection_topics"."navigation_observed_at" IS NULL OR "projection_topics"."navigation_observed_at" >= 0),
	CONSTRAINT "projection_topics_navigation_source_valid" CHECK("projection_topics"."navigation_source" IS NULL OR "projection_topics"."navigation_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_topics_preview_complete" CHECK((("projection_topics"."preview_data" IS NULL) = ("projection_topics"."preview_observed_at" IS NULL)) AND (("projection_topics"."preview_data" IS NULL) = ("projection_topics"."preview_source" IS NULL))),
	CONSTRAINT "projection_topics_preview_data_json" CHECK("projection_topics"."preview_data" IS NULL OR json_valid("projection_topics"."preview_data")),
	CONSTRAINT "projection_topics_preview_observed_at_positive" CHECK("projection_topics"."preview_observed_at" IS NULL OR "projection_topics"."preview_observed_at" >= 0),
	CONSTRAINT "projection_topics_preview_source_valid" CHECK("projection_topics"."preview_source" IS NULL OR "projection_topics"."preview_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_topics_routing_complete" CHECK((("projection_topics"."routing_data" IS NULL) = ("projection_topics"."routing_observed_at" IS NULL)) AND (("projection_topics"."routing_data" IS NULL) = ("projection_topics"."routing_source" IS NULL))),
	CONSTRAINT "projection_topics_routing_data_json" CHECK("projection_topics"."routing_data" IS NULL OR json_valid("projection_topics"."routing_data")),
	CONSTRAINT "projection_topics_routing_observed_at_positive" CHECK("projection_topics"."routing_observed_at" IS NULL OR "projection_topics"."routing_observed_at" >= 0),
	CONSTRAINT "projection_topics_routing_source_valid" CHECK("projection_topics"."routing_source" IS NULL OR "projection_topics"."routing_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_topics_run_timing_complete" CHECK((("projection_topics"."run_timing_data" IS NULL) = ("projection_topics"."run_timing_observed_at" IS NULL)) AND (("projection_topics"."run_timing_data" IS NULL) = ("projection_topics"."run_timing_source" IS NULL))),
	CONSTRAINT "projection_topics_run_timing_data_json" CHECK("projection_topics"."run_timing_data" IS NULL OR json_valid("projection_topics"."run_timing_data")),
	CONSTRAINT "projection_topics_run_timing_observed_at_positive" CHECK("projection_topics"."run_timing_observed_at" IS NULL OR "projection_topics"."run_timing_observed_at" >= 0),
	CONSTRAINT "projection_topics_run_timing_source_valid" CHECK("projection_topics"."run_timing_source" IS NULL OR "projection_topics"."run_timing_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_topics_status_complete" CHECK((("projection_topics"."status_data" IS NULL) = ("projection_topics"."status_observed_at" IS NULL)) AND (("projection_topics"."status_data" IS NULL) = ("projection_topics"."status_source" IS NULL))),
	CONSTRAINT "projection_topics_status_data_json" CHECK("projection_topics"."status_data" IS NULL OR json_valid("projection_topics"."status_data")),
	CONSTRAINT "projection_topics_status_observed_at_positive" CHECK("projection_topics"."status_observed_at" IS NULL OR "projection_topics"."status_observed_at" >= 0),
	CONSTRAINT "projection_topics_status_source_valid" CHECK("projection_topics"."status_source" IS NULL OR "projection_topics"."status_source" IN ('mutation', 'network', 'realtime'))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `projection_topics_scope_entity_unique` ON `projection_topics` (`scope`,`entity_id`);--> statement-breakpoint
CREATE INDEX `projection_topics_scope_idx` ON `projection_topics` (`scope`);