PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_projection_home_indexes` (
	`data` text NOT NULL,
	`key` text NOT NULL,
	`observed_at` integer NOT NULL,
	`schema_version` integer DEFAULT 1 NOT NULL,
	`scope` text NOT NULL,
	`source` text NOT NULL,
	`storage_id` text PRIMARY KEY NOT NULL,
	CONSTRAINT "projection_home_indexes_data_json" CHECK(json_valid("__new_projection_home_indexes"."data")),
	CONSTRAINT "projection_home_indexes_key_valid" CHECK("__new_projection_home_indexes"."key" IN ('agent.available', 'agent.directory', 'chatGroup.list', 'home.inboxTopics', 'home.recentTopics', 'home.sidebar', 'home.tasks', 'home.unresolvedBriefs') OR "__new_projection_home_indexes"."key" LIKE 'agent.search:%' OR "__new_projection_home_indexes"."key" LIKE 'brief.news:%' OR "__new_projection_home_indexes"."key" LIKE 'chat.agentViewTopics:%' OR "__new_projection_home_indexes"."key" LIKE 'chat.sidebarTopics:%' OR "__new_projection_home_indexes"."key" LIKE 'task.groupList:%' OR "__new_projection_home_indexes"."key" LIKE 'task.list:%'),
	CONSTRAINT "projection_home_indexes_observed_at_positive" CHECK("__new_projection_home_indexes"."observed_at" >= 0),
	CONSTRAINT "projection_home_indexes_schema_version_current" CHECK("__new_projection_home_indexes"."schema_version" = 1),
	CONSTRAINT "projection_home_indexes_source_valid" CHECK("__new_projection_home_indexes"."source" IN ('mutation', 'network', 'realtime'))
);
--> statement-breakpoint
INSERT INTO `__new_projection_home_indexes`("data", "key", "observed_at", "schema_version", "scope", "source", "storage_id") SELECT "data", "key", "observed_at", "schema_version", "scope", "source", "storage_id" FROM `projection_home_indexes`;--> statement-breakpoint
DROP TABLE `projection_home_indexes`;--> statement-breakpoint
ALTER TABLE `__new_projection_home_indexes` RENAME TO `projection_home_indexes`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE UNIQUE INDEX `projection_home_indexes_scope_key_unique` ON `projection_home_indexes` (`scope`,`key`);--> statement-breakpoint
CREATE INDEX `projection_home_indexes_scope_idx` ON `projection_home_indexes` (`scope`);--> statement-breakpoint
CREATE TABLE `__new_projection_agents` (
	`access_data` text,
	`access_observed_at` integer,
	`access_source` text,
	`configuration_data` text,
	`configuration_observed_at` integer,
	`configuration_source` text,
	`entity_id` text NOT NULL,
	`identity_data` text,
	`identity_observed_at` integer,
	`identity_source` text,
	`knowledge_data` text,
	`knowledge_observed_at` integer,
	`knowledge_source` text,
	`lifecycle_data` text,
	`lifecycle_observed_at` integer,
	`lifecycle_source` text,
	`profile_data` text,
	`profile_observed_at` integer,
	`profile_source` text,
	`routing_data` text,
	`routing_observed_at` integer,
	`routing_source` text,
	`runtime_data` text,
	`runtime_observed_at` integer,
	`runtime_source` text,
	`schema_version` integer DEFAULT 1 NOT NULL,
	`scope` text NOT NULL,
	`storage_id` text PRIMARY KEY NOT NULL,
	`tombstone_at` integer,
	CONSTRAINT "projection_agents_schema_version_current" CHECK("__new_projection_agents"."schema_version" = 1),
	CONSTRAINT "projection_agents_tombstone_at_positive" CHECK("__new_projection_agents"."tombstone_at" IS NULL OR "__new_projection_agents"."tombstone_at" >= 0),
	CONSTRAINT "projection_agents_access_complete" CHECK((("__new_projection_agents"."access_data" IS NULL) = ("__new_projection_agents"."access_observed_at" IS NULL)) AND (("__new_projection_agents"."access_data" IS NULL) = ("__new_projection_agents"."access_source" IS NULL))),
	CONSTRAINT "projection_agents_access_data_json" CHECK("__new_projection_agents"."access_data" IS NULL OR json_valid("__new_projection_agents"."access_data")),
	CONSTRAINT "projection_agents_access_observed_at_positive" CHECK("__new_projection_agents"."access_observed_at" IS NULL OR "__new_projection_agents"."access_observed_at" >= 0),
	CONSTRAINT "projection_agents_access_source_valid" CHECK("__new_projection_agents"."access_source" IS NULL OR "__new_projection_agents"."access_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_agents_configuration_complete" CHECK((("__new_projection_agents"."configuration_data" IS NULL) = ("__new_projection_agents"."configuration_observed_at" IS NULL)) AND (("__new_projection_agents"."configuration_data" IS NULL) = ("__new_projection_agents"."configuration_source" IS NULL))),
	CONSTRAINT "projection_agents_configuration_data_json" CHECK("__new_projection_agents"."configuration_data" IS NULL OR json_valid("__new_projection_agents"."configuration_data")),
	CONSTRAINT "projection_agents_configuration_observed_at_positive" CHECK("__new_projection_agents"."configuration_observed_at" IS NULL OR "__new_projection_agents"."configuration_observed_at" >= 0),
	CONSTRAINT "projection_agents_configuration_source_valid" CHECK("__new_projection_agents"."configuration_source" IS NULL OR "__new_projection_agents"."configuration_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_agents_identity_complete" CHECK((("__new_projection_agents"."identity_data" IS NULL) = ("__new_projection_agents"."identity_observed_at" IS NULL)) AND (("__new_projection_agents"."identity_data" IS NULL) = ("__new_projection_agents"."identity_source" IS NULL))),
	CONSTRAINT "projection_agents_identity_data_json" CHECK("__new_projection_agents"."identity_data" IS NULL OR json_valid("__new_projection_agents"."identity_data")),
	CONSTRAINT "projection_agents_identity_observed_at_positive" CHECK("__new_projection_agents"."identity_observed_at" IS NULL OR "__new_projection_agents"."identity_observed_at" >= 0),
	CONSTRAINT "projection_agents_identity_source_valid" CHECK("__new_projection_agents"."identity_source" IS NULL OR "__new_projection_agents"."identity_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_agents_knowledge_complete" CHECK((("__new_projection_agents"."knowledge_data" IS NULL) = ("__new_projection_agents"."knowledge_observed_at" IS NULL)) AND (("__new_projection_agents"."knowledge_data" IS NULL) = ("__new_projection_agents"."knowledge_source" IS NULL))),
	CONSTRAINT "projection_agents_knowledge_data_json" CHECK("__new_projection_agents"."knowledge_data" IS NULL OR json_valid("__new_projection_agents"."knowledge_data")),
	CONSTRAINT "projection_agents_knowledge_observed_at_positive" CHECK("__new_projection_agents"."knowledge_observed_at" IS NULL OR "__new_projection_agents"."knowledge_observed_at" >= 0),
	CONSTRAINT "projection_agents_knowledge_source_valid" CHECK("__new_projection_agents"."knowledge_source" IS NULL OR "__new_projection_agents"."knowledge_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_agents_lifecycle_complete" CHECK((("__new_projection_agents"."lifecycle_data" IS NULL) = ("__new_projection_agents"."lifecycle_observed_at" IS NULL)) AND (("__new_projection_agents"."lifecycle_data" IS NULL) = ("__new_projection_agents"."lifecycle_source" IS NULL))),
	CONSTRAINT "projection_agents_lifecycle_data_json" CHECK("__new_projection_agents"."lifecycle_data" IS NULL OR json_valid("__new_projection_agents"."lifecycle_data")),
	CONSTRAINT "projection_agents_lifecycle_observed_at_positive" CHECK("__new_projection_agents"."lifecycle_observed_at" IS NULL OR "__new_projection_agents"."lifecycle_observed_at" >= 0),
	CONSTRAINT "projection_agents_lifecycle_source_valid" CHECK("__new_projection_agents"."lifecycle_source" IS NULL OR "__new_projection_agents"."lifecycle_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_agents_profile_complete" CHECK((("__new_projection_agents"."profile_data" IS NULL) = ("__new_projection_agents"."profile_observed_at" IS NULL)) AND (("__new_projection_agents"."profile_data" IS NULL) = ("__new_projection_agents"."profile_source" IS NULL))),
	CONSTRAINT "projection_agents_profile_data_json" CHECK("__new_projection_agents"."profile_data" IS NULL OR json_valid("__new_projection_agents"."profile_data")),
	CONSTRAINT "projection_agents_profile_observed_at_positive" CHECK("__new_projection_agents"."profile_observed_at" IS NULL OR "__new_projection_agents"."profile_observed_at" >= 0),
	CONSTRAINT "projection_agents_profile_source_valid" CHECK("__new_projection_agents"."profile_source" IS NULL OR "__new_projection_agents"."profile_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_agents_routing_complete" CHECK((("__new_projection_agents"."routing_data" IS NULL) = ("__new_projection_agents"."routing_observed_at" IS NULL)) AND (("__new_projection_agents"."routing_data" IS NULL) = ("__new_projection_agents"."routing_source" IS NULL))),
	CONSTRAINT "projection_agents_routing_data_json" CHECK("__new_projection_agents"."routing_data" IS NULL OR json_valid("__new_projection_agents"."routing_data")),
	CONSTRAINT "projection_agents_routing_observed_at_positive" CHECK("__new_projection_agents"."routing_observed_at" IS NULL OR "__new_projection_agents"."routing_observed_at" >= 0),
	CONSTRAINT "projection_agents_routing_source_valid" CHECK("__new_projection_agents"."routing_source" IS NULL OR "__new_projection_agents"."routing_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_agents_runtime_complete" CHECK((("__new_projection_agents"."runtime_data" IS NULL) = ("__new_projection_agents"."runtime_observed_at" IS NULL)) AND (("__new_projection_agents"."runtime_data" IS NULL) = ("__new_projection_agents"."runtime_source" IS NULL))),
	CONSTRAINT "projection_agents_runtime_data_json" CHECK("__new_projection_agents"."runtime_data" IS NULL OR json_valid("__new_projection_agents"."runtime_data")),
	CONSTRAINT "projection_agents_runtime_observed_at_positive" CHECK("__new_projection_agents"."runtime_observed_at" IS NULL OR "__new_projection_agents"."runtime_observed_at" >= 0),
	CONSTRAINT "projection_agents_runtime_source_valid" CHECK("__new_projection_agents"."runtime_source" IS NULL OR "__new_projection_agents"."runtime_source" IN ('mutation', 'network', 'realtime'))
);
--> statement-breakpoint
INSERT INTO `__new_projection_agents`("access_data", "access_observed_at", "access_source", "configuration_data", "configuration_observed_at", "configuration_source", "entity_id", "identity_data", "identity_observed_at", "identity_source", "knowledge_data", "knowledge_observed_at", "knowledge_source", "lifecycle_data", "lifecycle_observed_at", "lifecycle_source", "profile_data", "profile_observed_at", "profile_source", "routing_data", "routing_observed_at", "routing_source", "runtime_data", "runtime_observed_at", "runtime_source", "schema_version", "scope", "storage_id", "tombstone_at") SELECT "access_data", "access_observed_at", "access_source", NULL, NULL, NULL, "entity_id", "identity_data", "identity_observed_at", "identity_source", NULL, NULL, NULL, NULL, NULL, NULL, "profile_data", "profile_observed_at", "profile_source", "routing_data", "routing_observed_at", "routing_source", "runtime_data", "runtime_observed_at", "runtime_source", "schema_version", "scope", "storage_id", "tombstone_at" FROM `projection_agents`;--> statement-breakpoint
DROP TABLE `projection_agents`;--> statement-breakpoint
ALTER TABLE `__new_projection_agents` RENAME TO `projection_agents`;--> statement-breakpoint
CREATE UNIQUE INDEX `projection_agents_scope_entity_unique` ON `projection_agents` (`scope`,`entity_id`);--> statement-breakpoint
CREATE INDEX `projection_agents_scope_idx` ON `projection_agents` (`scope`);--> statement-breakpoint
CREATE TABLE `__new_projection_chat_groups` (
	`access_data` text,
	`access_observed_at` integer,
	`access_source` text,
	`configuration_data` text,
	`configuration_observed_at` integer,
	`configuration_source` text,
	`entity_id` text NOT NULL,
	`identity_data` text,
	`identity_observed_at` integer,
	`identity_source` text,
	`lifecycle_data` text,
	`lifecycle_observed_at` integer,
	`lifecycle_source` text,
	`membership_data` text,
	`membership_observed_at` integer,
	`membership_source` text,
	`schema_version` integer DEFAULT 1 NOT NULL,
	`scope` text NOT NULL,
	`storage_id` text PRIMARY KEY NOT NULL,
	`tombstone_at` integer,
	CONSTRAINT "projection_chat_groups_schema_version_current" CHECK("__new_projection_chat_groups"."schema_version" = 1),
	CONSTRAINT "projection_chat_groups_tombstone_at_positive" CHECK("__new_projection_chat_groups"."tombstone_at" IS NULL OR "__new_projection_chat_groups"."tombstone_at" >= 0),
	CONSTRAINT "projection_chat_groups_access_complete" CHECK((("__new_projection_chat_groups"."access_data" IS NULL) = ("__new_projection_chat_groups"."access_observed_at" IS NULL)) AND (("__new_projection_chat_groups"."access_data" IS NULL) = ("__new_projection_chat_groups"."access_source" IS NULL))),
	CONSTRAINT "projection_chat_groups_access_data_json" CHECK("__new_projection_chat_groups"."access_data" IS NULL OR json_valid("__new_projection_chat_groups"."access_data")),
	CONSTRAINT "projection_chat_groups_access_observed_at_positive" CHECK("__new_projection_chat_groups"."access_observed_at" IS NULL OR "__new_projection_chat_groups"."access_observed_at" >= 0),
	CONSTRAINT "projection_chat_groups_access_source_valid" CHECK("__new_projection_chat_groups"."access_source" IS NULL OR "__new_projection_chat_groups"."access_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_chat_groups_configuration_complete" CHECK((("__new_projection_chat_groups"."configuration_data" IS NULL) = ("__new_projection_chat_groups"."configuration_observed_at" IS NULL)) AND (("__new_projection_chat_groups"."configuration_data" IS NULL) = ("__new_projection_chat_groups"."configuration_source" IS NULL))),
	CONSTRAINT "projection_chat_groups_configuration_data_json" CHECK("__new_projection_chat_groups"."configuration_data" IS NULL OR json_valid("__new_projection_chat_groups"."configuration_data")),
	CONSTRAINT "projection_chat_groups_configuration_observed_at_positive" CHECK("__new_projection_chat_groups"."configuration_observed_at" IS NULL OR "__new_projection_chat_groups"."configuration_observed_at" >= 0),
	CONSTRAINT "projection_chat_groups_configuration_source_valid" CHECK("__new_projection_chat_groups"."configuration_source" IS NULL OR "__new_projection_chat_groups"."configuration_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_chat_groups_identity_complete" CHECK((("__new_projection_chat_groups"."identity_data" IS NULL) = ("__new_projection_chat_groups"."identity_observed_at" IS NULL)) AND (("__new_projection_chat_groups"."identity_data" IS NULL) = ("__new_projection_chat_groups"."identity_source" IS NULL))),
	CONSTRAINT "projection_chat_groups_identity_data_json" CHECK("__new_projection_chat_groups"."identity_data" IS NULL OR json_valid("__new_projection_chat_groups"."identity_data")),
	CONSTRAINT "projection_chat_groups_identity_observed_at_positive" CHECK("__new_projection_chat_groups"."identity_observed_at" IS NULL OR "__new_projection_chat_groups"."identity_observed_at" >= 0),
	CONSTRAINT "projection_chat_groups_identity_source_valid" CHECK("__new_projection_chat_groups"."identity_source" IS NULL OR "__new_projection_chat_groups"."identity_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_chat_groups_lifecycle_complete" CHECK((("__new_projection_chat_groups"."lifecycle_data" IS NULL) = ("__new_projection_chat_groups"."lifecycle_observed_at" IS NULL)) AND (("__new_projection_chat_groups"."lifecycle_data" IS NULL) = ("__new_projection_chat_groups"."lifecycle_source" IS NULL))),
	CONSTRAINT "projection_chat_groups_lifecycle_data_json" CHECK("__new_projection_chat_groups"."lifecycle_data" IS NULL OR json_valid("__new_projection_chat_groups"."lifecycle_data")),
	CONSTRAINT "projection_chat_groups_lifecycle_observed_at_positive" CHECK("__new_projection_chat_groups"."lifecycle_observed_at" IS NULL OR "__new_projection_chat_groups"."lifecycle_observed_at" >= 0),
	CONSTRAINT "projection_chat_groups_lifecycle_source_valid" CHECK("__new_projection_chat_groups"."lifecycle_source" IS NULL OR "__new_projection_chat_groups"."lifecycle_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_chat_groups_membership_complete" CHECK((("__new_projection_chat_groups"."membership_data" IS NULL) = ("__new_projection_chat_groups"."membership_observed_at" IS NULL)) AND (("__new_projection_chat_groups"."membership_data" IS NULL) = ("__new_projection_chat_groups"."membership_source" IS NULL))),
	CONSTRAINT "projection_chat_groups_membership_data_json" CHECK("__new_projection_chat_groups"."membership_data" IS NULL OR json_valid("__new_projection_chat_groups"."membership_data")),
	CONSTRAINT "projection_chat_groups_membership_observed_at_positive" CHECK("__new_projection_chat_groups"."membership_observed_at" IS NULL OR "__new_projection_chat_groups"."membership_observed_at" >= 0),
	CONSTRAINT "projection_chat_groups_membership_source_valid" CHECK("__new_projection_chat_groups"."membership_source" IS NULL OR "__new_projection_chat_groups"."membership_source" IN ('mutation', 'network', 'realtime'))
);
--> statement-breakpoint
INSERT INTO `__new_projection_chat_groups`("access_data", "access_observed_at", "access_source", "configuration_data", "configuration_observed_at", "configuration_source", "entity_id", "identity_data", "identity_observed_at", "identity_source", "lifecycle_data", "lifecycle_observed_at", "lifecycle_source", "membership_data", "membership_observed_at", "membership_source", "schema_version", "scope", "storage_id", "tombstone_at") SELECT "access_data", "access_observed_at", "access_source", NULL, NULL, NULL, "entity_id", "identity_data", "identity_observed_at", "identity_source", NULL, NULL, NULL, NULL, NULL, NULL, "schema_version", "scope", "storage_id", "tombstone_at" FROM `projection_chat_groups`;--> statement-breakpoint
DROP TABLE `projection_chat_groups`;--> statement-breakpoint
ALTER TABLE `__new_projection_chat_groups` RENAME TO `projection_chat_groups`;--> statement-breakpoint
CREATE UNIQUE INDEX `projection_chat_groups_scope_entity_unique` ON `projection_chat_groups` (`scope`,`entity_id`);--> statement-breakpoint
CREATE INDEX `projection_chat_groups_scope_idx` ON `projection_chat_groups` (`scope`);--> statement-breakpoint
CREATE TABLE `__new_projection_tasks` (
	`assignment_data` text,
	`assignment_observed_at` integer,
	`assignment_source` text,
	`description_data` text,
	`description_observed_at` integer,
	`description_source` text,
	`detail_data` text,
	`detail_observed_at` integer,
	`detail_source` text,
	`display_data` text,
	`display_observed_at` integer,
	`display_source` text,
	`entity_id` text NOT NULL,
	`identity_data` text,
	`identity_observed_at` integer,
	`identity_source` text,
	`lifecycle_data` text,
	`lifecycle_observed_at` integer,
	`lifecycle_source` text,
	`participants_data` text,
	`participants_observed_at` integer,
	`participants_source` text,
	`row_data` text,
	`row_observed_at` integer,
	`row_source` text,
	`schema_version` integer DEFAULT 1 NOT NULL,
	`scope` text NOT NULL,
	`storage_id` text PRIMARY KEY NOT NULL,
	`tombstone_at` integer,
	CONSTRAINT "projection_tasks_schema_version_current" CHECK("__new_projection_tasks"."schema_version" = 1),
	CONSTRAINT "projection_tasks_tombstone_at_positive" CHECK("__new_projection_tasks"."tombstone_at" IS NULL OR "__new_projection_tasks"."tombstone_at" >= 0),
	CONSTRAINT "projection_tasks_assignment_complete" CHECK((("__new_projection_tasks"."assignment_data" IS NULL) = ("__new_projection_tasks"."assignment_observed_at" IS NULL)) AND (("__new_projection_tasks"."assignment_data" IS NULL) = ("__new_projection_tasks"."assignment_source" IS NULL))),
	CONSTRAINT "projection_tasks_assignment_data_json" CHECK("__new_projection_tasks"."assignment_data" IS NULL OR json_valid("__new_projection_tasks"."assignment_data")),
	CONSTRAINT "projection_tasks_assignment_observed_at_positive" CHECK("__new_projection_tasks"."assignment_observed_at" IS NULL OR "__new_projection_tasks"."assignment_observed_at" >= 0),
	CONSTRAINT "projection_tasks_assignment_source_valid" CHECK("__new_projection_tasks"."assignment_source" IS NULL OR "__new_projection_tasks"."assignment_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_tasks_description_complete" CHECK((("__new_projection_tasks"."description_data" IS NULL) = ("__new_projection_tasks"."description_observed_at" IS NULL)) AND (("__new_projection_tasks"."description_data" IS NULL) = ("__new_projection_tasks"."description_source" IS NULL))),
	CONSTRAINT "projection_tasks_description_data_json" CHECK("__new_projection_tasks"."description_data" IS NULL OR json_valid("__new_projection_tasks"."description_data")),
	CONSTRAINT "projection_tasks_description_observed_at_positive" CHECK("__new_projection_tasks"."description_observed_at" IS NULL OR "__new_projection_tasks"."description_observed_at" >= 0),
	CONSTRAINT "projection_tasks_description_source_valid" CHECK("__new_projection_tasks"."description_source" IS NULL OR "__new_projection_tasks"."description_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_tasks_detail_complete" CHECK((("__new_projection_tasks"."detail_data" IS NULL) = ("__new_projection_tasks"."detail_observed_at" IS NULL)) AND (("__new_projection_tasks"."detail_data" IS NULL) = ("__new_projection_tasks"."detail_source" IS NULL))),
	CONSTRAINT "projection_tasks_detail_data_json" CHECK("__new_projection_tasks"."detail_data" IS NULL OR json_valid("__new_projection_tasks"."detail_data")),
	CONSTRAINT "projection_tasks_detail_observed_at_positive" CHECK("__new_projection_tasks"."detail_observed_at" IS NULL OR "__new_projection_tasks"."detail_observed_at" >= 0),
	CONSTRAINT "projection_tasks_detail_source_valid" CHECK("__new_projection_tasks"."detail_source" IS NULL OR "__new_projection_tasks"."detail_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_tasks_display_complete" CHECK((("__new_projection_tasks"."display_data" IS NULL) = ("__new_projection_tasks"."display_observed_at" IS NULL)) AND (("__new_projection_tasks"."display_data" IS NULL) = ("__new_projection_tasks"."display_source" IS NULL))),
	CONSTRAINT "projection_tasks_display_data_json" CHECK("__new_projection_tasks"."display_data" IS NULL OR json_valid("__new_projection_tasks"."display_data")),
	CONSTRAINT "projection_tasks_display_observed_at_positive" CHECK("__new_projection_tasks"."display_observed_at" IS NULL OR "__new_projection_tasks"."display_observed_at" >= 0),
	CONSTRAINT "projection_tasks_display_source_valid" CHECK("__new_projection_tasks"."display_source" IS NULL OR "__new_projection_tasks"."display_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_tasks_identity_complete" CHECK((("__new_projection_tasks"."identity_data" IS NULL) = ("__new_projection_tasks"."identity_observed_at" IS NULL)) AND (("__new_projection_tasks"."identity_data" IS NULL) = ("__new_projection_tasks"."identity_source" IS NULL))),
	CONSTRAINT "projection_tasks_identity_data_json" CHECK("__new_projection_tasks"."identity_data" IS NULL OR json_valid("__new_projection_tasks"."identity_data")),
	CONSTRAINT "projection_tasks_identity_observed_at_positive" CHECK("__new_projection_tasks"."identity_observed_at" IS NULL OR "__new_projection_tasks"."identity_observed_at" >= 0),
	CONSTRAINT "projection_tasks_identity_source_valid" CHECK("__new_projection_tasks"."identity_source" IS NULL OR "__new_projection_tasks"."identity_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_tasks_lifecycle_complete" CHECK((("__new_projection_tasks"."lifecycle_data" IS NULL) = ("__new_projection_tasks"."lifecycle_observed_at" IS NULL)) AND (("__new_projection_tasks"."lifecycle_data" IS NULL) = ("__new_projection_tasks"."lifecycle_source" IS NULL))),
	CONSTRAINT "projection_tasks_lifecycle_data_json" CHECK("__new_projection_tasks"."lifecycle_data" IS NULL OR json_valid("__new_projection_tasks"."lifecycle_data")),
	CONSTRAINT "projection_tasks_lifecycle_observed_at_positive" CHECK("__new_projection_tasks"."lifecycle_observed_at" IS NULL OR "__new_projection_tasks"."lifecycle_observed_at" >= 0),
	CONSTRAINT "projection_tasks_lifecycle_source_valid" CHECK("__new_projection_tasks"."lifecycle_source" IS NULL OR "__new_projection_tasks"."lifecycle_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_tasks_participants_complete" CHECK((("__new_projection_tasks"."participants_data" IS NULL) = ("__new_projection_tasks"."participants_observed_at" IS NULL)) AND (("__new_projection_tasks"."participants_data" IS NULL) = ("__new_projection_tasks"."participants_source" IS NULL))),
	CONSTRAINT "projection_tasks_participants_data_json" CHECK("__new_projection_tasks"."participants_data" IS NULL OR json_valid("__new_projection_tasks"."participants_data")),
	CONSTRAINT "projection_tasks_participants_observed_at_positive" CHECK("__new_projection_tasks"."participants_observed_at" IS NULL OR "__new_projection_tasks"."participants_observed_at" >= 0),
	CONSTRAINT "projection_tasks_participants_source_valid" CHECK("__new_projection_tasks"."participants_source" IS NULL OR "__new_projection_tasks"."participants_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_tasks_row_complete" CHECK((("__new_projection_tasks"."row_data" IS NULL) = ("__new_projection_tasks"."row_observed_at" IS NULL)) AND (("__new_projection_tasks"."row_data" IS NULL) = ("__new_projection_tasks"."row_source" IS NULL))),
	CONSTRAINT "projection_tasks_row_data_json" CHECK("__new_projection_tasks"."row_data" IS NULL OR json_valid("__new_projection_tasks"."row_data")),
	CONSTRAINT "projection_tasks_row_observed_at_positive" CHECK("__new_projection_tasks"."row_observed_at" IS NULL OR "__new_projection_tasks"."row_observed_at" >= 0),
	CONSTRAINT "projection_tasks_row_source_valid" CHECK("__new_projection_tasks"."row_source" IS NULL OR "__new_projection_tasks"."row_source" IN ('mutation', 'network', 'realtime'))
);
--> statement-breakpoint
INSERT INTO `__new_projection_tasks`("assignment_data", "assignment_observed_at", "assignment_source", "description_data", "description_observed_at", "description_source", "detail_data", "detail_observed_at", "detail_source", "display_data", "display_observed_at", "display_source", "entity_id", "identity_data", "identity_observed_at", "identity_source", "lifecycle_data", "lifecycle_observed_at", "lifecycle_source", "participants_data", "participants_observed_at", "participants_source", "row_data", "row_observed_at", "row_source", "schema_version", "scope", "storage_id", "tombstone_at") SELECT "assignment_data", "assignment_observed_at", "assignment_source", "description_data", "description_observed_at", "description_source", NULL, NULL, NULL, "display_data", "display_observed_at", "display_source", "entity_id", "identity_data", "identity_observed_at", "identity_source", "lifecycle_data", "lifecycle_observed_at", "lifecycle_source", NULL, NULL, NULL, NULL, NULL, NULL, "schema_version", "scope", "storage_id", "tombstone_at" FROM `projection_tasks`;--> statement-breakpoint
DROP TABLE `projection_tasks`;--> statement-breakpoint
ALTER TABLE `__new_projection_tasks` RENAME TO `projection_tasks`;--> statement-breakpoint
CREATE UNIQUE INDEX `projection_tasks_scope_entity_unique` ON `projection_tasks` (`scope`,`entity_id`);--> statement-breakpoint
CREATE INDEX `projection_tasks_scope_idx` ON `projection_tasks` (`scope`);--> statement-breakpoint
CREATE TABLE `__new_projection_topics` (
	`activity_data` text,
	`activity_observed_at` integer,
	`activity_source` text,
	`analytics_data` text,
	`analytics_observed_at` integer,
	`analytics_source` text,
	`completion_data` text,
	`completion_observed_at` integer,
	`completion_source` text,
	`creation_data` text,
	`creation_observed_at` integer,
	`creation_source` text,
	`details_data` text,
	`details_observed_at` integer,
	`details_source` text,
	`display_data` text,
	`display_observed_at` integer,
	`display_source` text,
	`entity_id` text NOT NULL,
	`generation_data` text,
	`generation_observed_at` integer,
	`generation_source` text,
	`marking_data` text,
	`marking_observed_at` integer,
	`marking_source` text,
	`navigation_data` text,
	`navigation_observed_at` integer,
	`navigation_source` text,
	`ordering_data` text,
	`ordering_observed_at` integer,
	`ordering_source` text,
	`ownership_data` text,
	`ownership_observed_at` integer,
	`ownership_source` text,
	`preview_data` text,
	`preview_observed_at` integer,
	`preview_source` text,
	`routing_data` text,
	`routing_observed_at` integer,
	`routing_source` text,
	`run_timing_data` text,
	`run_timing_observed_at` integer,
	`run_timing_source` text,
	`schema_version` integer DEFAULT 1 NOT NULL,
	`scope` text NOT NULL,
	`status_data` text,
	`status_observed_at` integer,
	`status_source` text,
	`storage_id` text PRIMARY KEY NOT NULL,
	`summary_data` text,
	`summary_observed_at` integer,
	`summary_source` text,
	`tombstone_at` integer,
	`trigger_info_data` text,
	`trigger_info_observed_at` integer,
	`trigger_info_source` text,
	CONSTRAINT "projection_topics_schema_version_current" CHECK("__new_projection_topics"."schema_version" = 1),
	CONSTRAINT "projection_topics_tombstone_at_positive" CHECK("__new_projection_topics"."tombstone_at" IS NULL OR "__new_projection_topics"."tombstone_at" >= 0),
	CONSTRAINT "projection_topics_activity_complete" CHECK((("__new_projection_topics"."activity_data" IS NULL) = ("__new_projection_topics"."activity_observed_at" IS NULL)) AND (("__new_projection_topics"."activity_data" IS NULL) = ("__new_projection_topics"."activity_source" IS NULL))),
	CONSTRAINT "projection_topics_activity_data_json" CHECK("__new_projection_topics"."activity_data" IS NULL OR json_valid("__new_projection_topics"."activity_data")),
	CONSTRAINT "projection_topics_activity_observed_at_positive" CHECK("__new_projection_topics"."activity_observed_at" IS NULL OR "__new_projection_topics"."activity_observed_at" >= 0),
	CONSTRAINT "projection_topics_activity_source_valid" CHECK("__new_projection_topics"."activity_source" IS NULL OR "__new_projection_topics"."activity_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_topics_analytics_complete" CHECK((("__new_projection_topics"."analytics_data" IS NULL) = ("__new_projection_topics"."analytics_observed_at" IS NULL)) AND (("__new_projection_topics"."analytics_data" IS NULL) = ("__new_projection_topics"."analytics_source" IS NULL))),
	CONSTRAINT "projection_topics_analytics_data_json" CHECK("__new_projection_topics"."analytics_data" IS NULL OR json_valid("__new_projection_topics"."analytics_data")),
	CONSTRAINT "projection_topics_analytics_observed_at_positive" CHECK("__new_projection_topics"."analytics_observed_at" IS NULL OR "__new_projection_topics"."analytics_observed_at" >= 0),
	CONSTRAINT "projection_topics_analytics_source_valid" CHECK("__new_projection_topics"."analytics_source" IS NULL OR "__new_projection_topics"."analytics_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_topics_completion_complete" CHECK((("__new_projection_topics"."completion_data" IS NULL) = ("__new_projection_topics"."completion_observed_at" IS NULL)) AND (("__new_projection_topics"."completion_data" IS NULL) = ("__new_projection_topics"."completion_source" IS NULL))),
	CONSTRAINT "projection_topics_completion_data_json" CHECK("__new_projection_topics"."completion_data" IS NULL OR json_valid("__new_projection_topics"."completion_data")),
	CONSTRAINT "projection_topics_completion_observed_at_positive" CHECK("__new_projection_topics"."completion_observed_at" IS NULL OR "__new_projection_topics"."completion_observed_at" >= 0),
	CONSTRAINT "projection_topics_completion_source_valid" CHECK("__new_projection_topics"."completion_source" IS NULL OR "__new_projection_topics"."completion_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_topics_creation_complete" CHECK((("__new_projection_topics"."creation_data" IS NULL) = ("__new_projection_topics"."creation_observed_at" IS NULL)) AND (("__new_projection_topics"."creation_data" IS NULL) = ("__new_projection_topics"."creation_source" IS NULL))),
	CONSTRAINT "projection_topics_creation_data_json" CHECK("__new_projection_topics"."creation_data" IS NULL OR json_valid("__new_projection_topics"."creation_data")),
	CONSTRAINT "projection_topics_creation_observed_at_positive" CHECK("__new_projection_topics"."creation_observed_at" IS NULL OR "__new_projection_topics"."creation_observed_at" >= 0),
	CONSTRAINT "projection_topics_creation_source_valid" CHECK("__new_projection_topics"."creation_source" IS NULL OR "__new_projection_topics"."creation_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_topics_details_complete" CHECK((("__new_projection_topics"."details_data" IS NULL) = ("__new_projection_topics"."details_observed_at" IS NULL)) AND (("__new_projection_topics"."details_data" IS NULL) = ("__new_projection_topics"."details_source" IS NULL))),
	CONSTRAINT "projection_topics_details_data_json" CHECK("__new_projection_topics"."details_data" IS NULL OR json_valid("__new_projection_topics"."details_data")),
	CONSTRAINT "projection_topics_details_observed_at_positive" CHECK("__new_projection_topics"."details_observed_at" IS NULL OR "__new_projection_topics"."details_observed_at" >= 0),
	CONSTRAINT "projection_topics_details_source_valid" CHECK("__new_projection_topics"."details_source" IS NULL OR "__new_projection_topics"."details_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_topics_display_complete" CHECK((("__new_projection_topics"."display_data" IS NULL) = ("__new_projection_topics"."display_observed_at" IS NULL)) AND (("__new_projection_topics"."display_data" IS NULL) = ("__new_projection_topics"."display_source" IS NULL))),
	CONSTRAINT "projection_topics_display_data_json" CHECK("__new_projection_topics"."display_data" IS NULL OR json_valid("__new_projection_topics"."display_data")),
	CONSTRAINT "projection_topics_display_observed_at_positive" CHECK("__new_projection_topics"."display_observed_at" IS NULL OR "__new_projection_topics"."display_observed_at" >= 0),
	CONSTRAINT "projection_topics_display_source_valid" CHECK("__new_projection_topics"."display_source" IS NULL OR "__new_projection_topics"."display_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_topics_generation_complete" CHECK((("__new_projection_topics"."generation_data" IS NULL) = ("__new_projection_topics"."generation_observed_at" IS NULL)) AND (("__new_projection_topics"."generation_data" IS NULL) = ("__new_projection_topics"."generation_source" IS NULL))),
	CONSTRAINT "projection_topics_generation_data_json" CHECK("__new_projection_topics"."generation_data" IS NULL OR json_valid("__new_projection_topics"."generation_data")),
	CONSTRAINT "projection_topics_generation_observed_at_positive" CHECK("__new_projection_topics"."generation_observed_at" IS NULL OR "__new_projection_topics"."generation_observed_at" >= 0),
	CONSTRAINT "projection_topics_generation_source_valid" CHECK("__new_projection_topics"."generation_source" IS NULL OR "__new_projection_topics"."generation_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_topics_marking_complete" CHECK((("__new_projection_topics"."marking_data" IS NULL) = ("__new_projection_topics"."marking_observed_at" IS NULL)) AND (("__new_projection_topics"."marking_data" IS NULL) = ("__new_projection_topics"."marking_source" IS NULL))),
	CONSTRAINT "projection_topics_marking_data_json" CHECK("__new_projection_topics"."marking_data" IS NULL OR json_valid("__new_projection_topics"."marking_data")),
	CONSTRAINT "projection_topics_marking_observed_at_positive" CHECK("__new_projection_topics"."marking_observed_at" IS NULL OR "__new_projection_topics"."marking_observed_at" >= 0),
	CONSTRAINT "projection_topics_marking_source_valid" CHECK("__new_projection_topics"."marking_source" IS NULL OR "__new_projection_topics"."marking_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_topics_navigation_complete" CHECK((("__new_projection_topics"."navigation_data" IS NULL) = ("__new_projection_topics"."navigation_observed_at" IS NULL)) AND (("__new_projection_topics"."navigation_data" IS NULL) = ("__new_projection_topics"."navigation_source" IS NULL))),
	CONSTRAINT "projection_topics_navigation_data_json" CHECK("__new_projection_topics"."navigation_data" IS NULL OR json_valid("__new_projection_topics"."navigation_data")),
	CONSTRAINT "projection_topics_navigation_observed_at_positive" CHECK("__new_projection_topics"."navigation_observed_at" IS NULL OR "__new_projection_topics"."navigation_observed_at" >= 0),
	CONSTRAINT "projection_topics_navigation_source_valid" CHECK("__new_projection_topics"."navigation_source" IS NULL OR "__new_projection_topics"."navigation_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_topics_ordering_complete" CHECK((("__new_projection_topics"."ordering_data" IS NULL) = ("__new_projection_topics"."ordering_observed_at" IS NULL)) AND (("__new_projection_topics"."ordering_data" IS NULL) = ("__new_projection_topics"."ordering_source" IS NULL))),
	CONSTRAINT "projection_topics_ordering_data_json" CHECK("__new_projection_topics"."ordering_data" IS NULL OR json_valid("__new_projection_topics"."ordering_data")),
	CONSTRAINT "projection_topics_ordering_observed_at_positive" CHECK("__new_projection_topics"."ordering_observed_at" IS NULL OR "__new_projection_topics"."ordering_observed_at" >= 0),
	CONSTRAINT "projection_topics_ordering_source_valid" CHECK("__new_projection_topics"."ordering_source" IS NULL OR "__new_projection_topics"."ordering_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_topics_ownership_complete" CHECK((("__new_projection_topics"."ownership_data" IS NULL) = ("__new_projection_topics"."ownership_observed_at" IS NULL)) AND (("__new_projection_topics"."ownership_data" IS NULL) = ("__new_projection_topics"."ownership_source" IS NULL))),
	CONSTRAINT "projection_topics_ownership_data_json" CHECK("__new_projection_topics"."ownership_data" IS NULL OR json_valid("__new_projection_topics"."ownership_data")),
	CONSTRAINT "projection_topics_ownership_observed_at_positive" CHECK("__new_projection_topics"."ownership_observed_at" IS NULL OR "__new_projection_topics"."ownership_observed_at" >= 0),
	CONSTRAINT "projection_topics_ownership_source_valid" CHECK("__new_projection_topics"."ownership_source" IS NULL OR "__new_projection_topics"."ownership_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_topics_preview_complete" CHECK((("__new_projection_topics"."preview_data" IS NULL) = ("__new_projection_topics"."preview_observed_at" IS NULL)) AND (("__new_projection_topics"."preview_data" IS NULL) = ("__new_projection_topics"."preview_source" IS NULL))),
	CONSTRAINT "projection_topics_preview_data_json" CHECK("__new_projection_topics"."preview_data" IS NULL OR json_valid("__new_projection_topics"."preview_data")),
	CONSTRAINT "projection_topics_preview_observed_at_positive" CHECK("__new_projection_topics"."preview_observed_at" IS NULL OR "__new_projection_topics"."preview_observed_at" >= 0),
	CONSTRAINT "projection_topics_preview_source_valid" CHECK("__new_projection_topics"."preview_source" IS NULL OR "__new_projection_topics"."preview_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_topics_routing_complete" CHECK((("__new_projection_topics"."routing_data" IS NULL) = ("__new_projection_topics"."routing_observed_at" IS NULL)) AND (("__new_projection_topics"."routing_data" IS NULL) = ("__new_projection_topics"."routing_source" IS NULL))),
	CONSTRAINT "projection_topics_routing_data_json" CHECK("__new_projection_topics"."routing_data" IS NULL OR json_valid("__new_projection_topics"."routing_data")),
	CONSTRAINT "projection_topics_routing_observed_at_positive" CHECK("__new_projection_topics"."routing_observed_at" IS NULL OR "__new_projection_topics"."routing_observed_at" >= 0),
	CONSTRAINT "projection_topics_routing_source_valid" CHECK("__new_projection_topics"."routing_source" IS NULL OR "__new_projection_topics"."routing_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_topics_run_timing_complete" CHECK((("__new_projection_topics"."run_timing_data" IS NULL) = ("__new_projection_topics"."run_timing_observed_at" IS NULL)) AND (("__new_projection_topics"."run_timing_data" IS NULL) = ("__new_projection_topics"."run_timing_source" IS NULL))),
	CONSTRAINT "projection_topics_run_timing_data_json" CHECK("__new_projection_topics"."run_timing_data" IS NULL OR json_valid("__new_projection_topics"."run_timing_data")),
	CONSTRAINT "projection_topics_run_timing_observed_at_positive" CHECK("__new_projection_topics"."run_timing_observed_at" IS NULL OR "__new_projection_topics"."run_timing_observed_at" >= 0),
	CONSTRAINT "projection_topics_run_timing_source_valid" CHECK("__new_projection_topics"."run_timing_source" IS NULL OR "__new_projection_topics"."run_timing_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_topics_status_complete" CHECK((("__new_projection_topics"."status_data" IS NULL) = ("__new_projection_topics"."status_observed_at" IS NULL)) AND (("__new_projection_topics"."status_data" IS NULL) = ("__new_projection_topics"."status_source" IS NULL))),
	CONSTRAINT "projection_topics_status_data_json" CHECK("__new_projection_topics"."status_data" IS NULL OR json_valid("__new_projection_topics"."status_data")),
	CONSTRAINT "projection_topics_status_observed_at_positive" CHECK("__new_projection_topics"."status_observed_at" IS NULL OR "__new_projection_topics"."status_observed_at" >= 0),
	CONSTRAINT "projection_topics_status_source_valid" CHECK("__new_projection_topics"."status_source" IS NULL OR "__new_projection_topics"."status_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_topics_summary_complete" CHECK((("__new_projection_topics"."summary_data" IS NULL) = ("__new_projection_topics"."summary_observed_at" IS NULL)) AND (("__new_projection_topics"."summary_data" IS NULL) = ("__new_projection_topics"."summary_source" IS NULL))),
	CONSTRAINT "projection_topics_summary_data_json" CHECK("__new_projection_topics"."summary_data" IS NULL OR json_valid("__new_projection_topics"."summary_data")),
	CONSTRAINT "projection_topics_summary_observed_at_positive" CHECK("__new_projection_topics"."summary_observed_at" IS NULL OR "__new_projection_topics"."summary_observed_at" >= 0),
	CONSTRAINT "projection_topics_summary_source_valid" CHECK("__new_projection_topics"."summary_source" IS NULL OR "__new_projection_topics"."summary_source" IN ('mutation', 'network', 'realtime')),
	CONSTRAINT "projection_topics_trigger_info_complete" CHECK((("__new_projection_topics"."trigger_info_data" IS NULL) = ("__new_projection_topics"."trigger_info_observed_at" IS NULL)) AND (("__new_projection_topics"."trigger_info_data" IS NULL) = ("__new_projection_topics"."trigger_info_source" IS NULL))),
	CONSTRAINT "projection_topics_trigger_info_data_json" CHECK("__new_projection_topics"."trigger_info_data" IS NULL OR json_valid("__new_projection_topics"."trigger_info_data")),
	CONSTRAINT "projection_topics_trigger_info_observed_at_positive" CHECK("__new_projection_topics"."trigger_info_observed_at" IS NULL OR "__new_projection_topics"."trigger_info_observed_at" >= 0),
	CONSTRAINT "projection_topics_trigger_info_source_valid" CHECK("__new_projection_topics"."trigger_info_source" IS NULL OR "__new_projection_topics"."trigger_info_source" IN ('mutation', 'network', 'realtime'))
);
--> statement-breakpoint
INSERT INTO `__new_projection_topics`("activity_data", "activity_observed_at", "activity_source", "analytics_data", "analytics_observed_at", "analytics_source", "completion_data", "completion_observed_at", "completion_source", "creation_data", "creation_observed_at", "creation_source", "details_data", "details_observed_at", "details_source", "display_data", "display_observed_at", "display_source", "entity_id", "generation_data", "generation_observed_at", "generation_source", "marking_data", "marking_observed_at", "marking_source", "navigation_data", "navigation_observed_at", "navigation_source", "ordering_data", "ordering_observed_at", "ordering_source", "ownership_data", "ownership_observed_at", "ownership_source", "preview_data", "preview_observed_at", "preview_source", "routing_data", "routing_observed_at", "routing_source", "run_timing_data", "run_timing_observed_at", "run_timing_source", "schema_version", "scope", "status_data", "status_observed_at", "status_source", "storage_id", "summary_data", "summary_observed_at", "summary_source", "tombstone_at", "trigger_info_data", "trigger_info_observed_at", "trigger_info_source") SELECT "activity_data", "activity_observed_at", "activity_source", NULL, NULL, NULL, NULL, NULL, NULL, "creation_data", "creation_observed_at", "creation_source", NULL, NULL, NULL, "display_data", "display_observed_at", "display_source", "entity_id", NULL, NULL, NULL, NULL, NULL, NULL, "navigation_data", "navigation_observed_at", "navigation_source", NULL, NULL, NULL, NULL, NULL, NULL, "preview_data", "preview_observed_at", "preview_source", "routing_data", "routing_observed_at", "routing_source", "run_timing_data", "run_timing_observed_at", "run_timing_source", "schema_version", "scope", "status_data", "status_observed_at", "status_source", "storage_id", NULL, NULL, NULL, "tombstone_at", NULL, NULL, NULL FROM `projection_topics`;--> statement-breakpoint
DROP TABLE `projection_topics`;--> statement-breakpoint
ALTER TABLE `__new_projection_topics` RENAME TO `projection_topics`;--> statement-breakpoint
CREATE UNIQUE INDEX `projection_topics_scope_entity_unique` ON `projection_topics` (`scope`,`entity_id`);--> statement-breakpoint
CREATE INDEX `projection_topics_scope_idx` ON `projection_topics` (`scope`);
